### ISSUE TITLE
Орфографическая ошибка в выводе

### ISSUE THREAD

**Issue by bilskla** [User1Root/AccountingSystem#10]
1. Запускаем проект, вводим тестовые логин и пароль (предоставленные нам "2" и "123" соответственно), нажимаем на кнопку "Найти ЭНИ", вводим номер ЭНИ 1231233. Нам открывается окно информации об этом ЭНИ, и мы наблюдаем орфографическую ошибку в слове "последнего"
![image](https://user-images.githubusercontent.com/71009109/100897779-1d574580-34d1-11eb-8d25-04e7cc8148d0.png)
2. Ожидаемый результат - орфографическая ошибка исправлена

**Comment by qbk3** [comment]
Исправил 03.12.20
