### ISSUE TITLE
Кнопка "Разлогиниться" не выполняет указанную функцию

### ISSUE THREAD

**Issue by bilskla** [User1Root/AccountingSystem#11]
1. Запускаем проект, вводим тестовые логин и пароль (предоставленные нам "2" и "123" соответственно), а затем имитируем работу программы с использованием ЭНИ №1231233. После выполнения нескольких действий нам нужно передать управлению другому пользователю, но после нажатия на кнопку "Разлогиниться" мы не возвращаемся на форму ввода логина и пароля, а отсчитываем назад все пройденные действия (можно увидеть на видео - https://youtu.be/Vdphe19l1F4, так как GitHub не разрешает загружать видеофайлы). Тип ошибки - нарушение внутренней логики работы ПО
2. Ожидаемый результат - кнопка "Разлогиниться" выполняет выход из аккаунта и возвращает на форму авторизации

**Comment by qbk3** [comment]
Исправил 03.12.20
