### ISSUE TITLE
Некорректное отображение контента в полноэкранном режиме

### ISSUE THREAD

**Issue by bilskla** [User1Root/AccountingSystem#12]
1. Запускаем проект, вводим тестовые логин и пароль (предоставленные нам "2" и "123" соответственно), затем кнопкой в правом верхнем углу включаем полноэкранный режим.
Общая ошибка - в левом верхнем улгу в меню выпадающее меню выбора города не меняет свой размер:
![image](https://user-images.githubusercontent.com/71009109/100901210-a754dd80-34d4-11eb-9211-d9b8a84cb5b2.png)
В меню "ЭНИ в депо" выводимая в окно вывода информация фиксированной длины, расстояние между кнопками справа разное:
![image](https://user-images.githubusercontent.com/71009109/100901415-d703e580-34d4-11eb-8f0f-1948043cf7a7.png)
В меню "Добавить ЭНИ" и "Выдать ЭНИ" одинаковая ошибка - расстояние между надписью "Номер ЭНИ" и блоком ввода самого номера ЭНИ больше, чем между этой же подписью и блоком ввода номера водителя:
![image](https://user-images.githubusercontent.com/71009109/100901576-04e92a00-34d5-11eb-8851-7a2a4a91b4df.png)
(тип ошибки - визуальная)
2. Ожидаемый результат - контент отображается корректно после изменения на полноэкранный режим

**Comment by qbk3** [comment]
Исправил 03.12.20
