### ISSUE TITLE
Некорректное отображение элементов в формах ввода

### ISSUE THREAD

**Issue by bilskla** [User1Root/AccountingSystem#4]
1. Запускаем проект, появляется форма ввода логина и пароля для оператора. При вводе в любое из этих полей текст выравнивается не по центру (относительно средней линии фигуры), а по верхней границе поля (тип ошибки - визуальная)
![image](https://user-images.githubusercontent.com/71009109/100882640-78cd0780-34c0-11eb-8333-887350276aab.png)
2. Ожидаемый результат - символы в обоих полях выравниваются по центру относительно верхней границы поля

**Comment by qbk3** [comment]
Исправил 03.12.20
