### ISSUE TITLE
Некорректное отображение текста на кнопке

### ISSUE THREAD

**Issue by bilskla** [User1Root/AccountingSystem#5]
1. Запускаем проект, вводим тестовые логин и пароль (предоставленные нам "1" и "123" соответственно), нажимаем на кнопку "ЭНИ в депо". Видим на кнопке "Эни из других депо", что текст вышел за предел кнопки (тип ошибки - визуальная)
![Untitled](https://user-images.githubusercontent.com/71009109/100883967-fe04ec00-34c1-11eb-83f5-bafa820b5863.png)
2. Ожидаемый результат - текст отображается корректно, не выходя за пределы кнопки

**Comment by qbk3** [comment]
Исправил 03.12.20
