### ISSUE TITLE
Ошибка в написании аббревиатуры

### ISSUE THREAD

**Issue by bilskla** [User1Root/AccountingSystem#6]
1. Запускаем проект, вводим тестовые логин и пароль (предоставленные нам "1" и "123" соответственно), нажимаем на кнопку "ЭНИ в депо". На кнопках "ЭНИ в депо" и "ЭНИ в поездке" аббревиатура (ЭНИ - электронный носитель информации) написана корректно, на кнопке "Эни из других депо" - нет. Аналогичная ситуация в меню слева на кнопках "Добавить Эни" и "Выдать Эни" (тип ошибки - ошибка контента)
![Untitled](https://user-images.githubusercontent.com/71009109/100884929-1f1a0c80-34c3-11eb-849b-8fdef1d265fb.png)
2. Ожидаемый результат - аббревиатуры написаны корректно, следуя правилам русского языка

**Comment by qbk3** [comment]
Исправил 03.12.20
