### ISSUE TITLE
Сброс результатов поиска после просмотра подробной информации

### ISSUE THREAD

**Issue by bilskla** [User1Root/AccountingSystem#7]
1. Запускаем проект, вводим тестовые логин и пароль (предоставленные нам "1" и "123" соответственно), выбираем город из выпадающего списка "11: Лоста", нажимаем на кнопку "ЭНИ в депо". Далее нажимаем на кнопку "ЭНИ в депо" в правой панели и видим два ЭНИ - номера 1231231 и 1231232.
![Untitled2](https://user-images.githubusercontent.com/71009109/100888937-ac5f6000-34c7-11eb-8395-9d801e44d0d1.png)
Нажимаем на кнопку "Подробнее" у ЭНИ 1231231 (фактически работает с любым ЭНИ), и при нажатии на кнопку "Назад" в появившемся меню нас перемещает назад...
![image](https://user-images.githubusercontent.com/71009109/100889042-c436e400-34c7-11eb-9e39-08c41abe6492.png)
...но при этом вся информация о только что найденных ЭМИ сбросилась, из-за чего нужно повторно нажать на кнопку "ЭНИ в депо" (тип ошибки - ошибка удобства использования)
![image](https://user-images.githubusercontent.com/71009109/100889129-dadd3b00-34c7-11eb-9bc3-4726affc1d1d.png)
2. Ожидаемый результат - после нажатия на кнопку "Назад" мы возвращаемся в меню "ЭНИ в депо", и последние результаты поиска сохраняются

**Comment by Alexashka21** [comment]
Исправил 05.12.20
