### ISSUE TITLE
Некорректное название выполняемого действия (возможно, не ошибка)

### ISSUE THREAD

**Issue by bilskla** [User1Root/AccountingSystem#8]
1. Запускаем проект, вводим тестовые логин и пароль (предоставленные нам "2" и "123" соответственно). Текущая задача: выдать ЭНИ водителю, и позже его забрать (имитация поездки). Используя данные из базы данных (водитель 12312313 Игорь Войтенко и ЭНИ №1231233) мы выдаем ему ЭНИ:
![image](https://user-images.githubusercontent.com/71009109/100892923-e03c8480-34cb-11eb-8204-82b8a9867768.png)
Еще перед тестовым действием наша команда не могла понять, как именно выдавать и забирать ЭНИ, и методом тыка мы поняли, что "Выдать ЭНИ" - это выдать ЭНИ, что очень логично, однако забрать ЭНИ - это "Добавить ЭНИ". Вероятно, тут использовалась логика "Добавить ЭНИ в базу данных" как незанятую, однако поначалу этого не поняли.
2. Рекомендуется (необязательно) поменять формулировку кнопки возврата ЭНИ, однако мы неопытные юзеры, и специально обученный человек _возможно_ не увидит в этом какой-либо ошибки

**Comment by qbk3** [comment]
Исправил 03.12.20
