### ISSUE TITLE
Некорректное отображение полосы прокрутки у формы вывода информации

### ISSUE THREAD

**Issue by bilskla** [User1Root/AccountingSystem#9]
1. Запускаем проект, вводим тестовые логин и пароль (предоставленные нам "2" и "123" соответственно), нажимаем на кнопку "ЭНИ в депо" и переходим на страницу проверки перемещаемых ЭНИ. Наблюдаем, что полоса прокрутки содержимого (так называемый "скролл") немного вылезает за правый верхний угол формы вывода информации
![Untitled3](https://user-images.githubusercontent.com/71009109/100894986-21359880-34ce-11eb-8ce3-0634b4009dc7.png)
2. Ожидаемое действие - либо убрать скругление у формы ввода, либо сдвинуть скролл немного влево

> Точность - вежливость королей

**Comment by qbk3** [comment]
Исправил 03.12.20
